### ISSUE TITLE
OneDrive uninstaller doesn't remove OneDrive from the file explorer

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/Win10Clean#1]
Seems like the OneDrive uninstaller doesn't remove itself from Explorer when looking in a open file dialog, didn't notice this until today, as I reinstalled Windows on my computer (had to be done)

**Comment by HawaiiBeach** [comment]
Reopened because OneDrive doesn't vanish from [FolderBrowserDialog](https://msdn.microsoft.com/en-us/library/system.windows.forms.folderbrowserdialog.aspx)

![psfile](https://cloud.githubusercontent.com/assets/12564301/23210767/5a086fd4-f8ff-11e6-894f-efa1f200541d.png)

**Comment by HawaiiBeach** [comment]
So I found a fix, but requires us to delete registry keys, and is something I'd not want to add in the application... Lemme see if I can do something about it.....

**Comment by HawaiiBeach** [comment]
Found a solution! Working on the code now . . .

**Comment by HawaiiBeach** [comment]
![after](https://cloud.githubusercontent.com/assets/12564301/23227821/88432b92-f93a-11e6-837f-1ab04851893b.png)
Mom I did it!

QA and I'll push a commit

**Comment by HawaiiBeach** [comment]
So this issue just appared yet again! Weird isn't it...

**Comment by HawaiiBeach** [comment]
Seems like adding the amd64 keys (if applicable) fixes this issue.

**Comment by HawaiiBeach** [comment]
So I've tried to re-produce this bug on a VM without success..
