### ISSUE TITLE
How to restore edit in notepad context menu?

### ISSUE THREAD

**Issue by necros2k7** [ElPumpo/Win10Clean#10]
subj

**Comment by HawaiiBeach** [comment]
What is "subj"? On what file types do you want to restore it on?

**Comment by necros2k7** [comment]
subj means message is the same as title 
Want to restore it on *.cmd files

**Comment by HawaiiBeach** [comment]
Restoring changes... this is what deadmoon was doing in a branch I deleted some time ago. I don't think I'll ever add that back in, because of how I've written the code.

**Comment by HawaiiBeach** [comment]
Not going to happen, too much work and it was primarly developed for myself
