### ISSUE TITLE
Changes in fall creators update

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/Win10Clean#7]
- [x] share context menu `HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\ModernSharing`
- [x] hide my people from taskbar `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\People`
- [x] 3d builder libary in my pc
- [x] ads in start menu `HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager\SubscribedContent-338388Enabled`

**Comment by hellzerg** [comment]
3D objects removed!
